Task 1
IlyaMuravjov/formal-lang-course pull request #1
Opened 2022-09-11 12:36 UTC by IlyaMuravjov

Solved [task1](https://github.com/IlyaMuravjov/formal-lang-course/blob/task1/tasks/task1.md).

2022-09-11 16:29 UTC, vadyushkins requested changes

2022-09-11 16:29 UTC, vadyushkins commented on .github/workflows/test.yml
> +    runs-on: ubuntu-latest
Добавьте windows, macos

2022-09-11 16:29 UTC, vadyushkins commented on project/task1.py
> +    """
Вы либо пишите полностью документацию для всех функций (что на мой взгляд сложнее), либо не пишите вообще (тогда самодокументирующийся, то есть понятный читабельный код)

2022-09-11 16:29 UTC, vadyushkins commented on requirements.txt
> +networkx
Уже импортируется в cfpq-data

2022-09-11 16:29 UTC, vadyushkins commented on tests/test_task1.py
> +    assert actual_graph_data == expected_graph_data
Попробуйте больше разных графов (в том числе интересуют крайние случаи).

2022-09-11 16:29 UTC, vadyushkins commented on tests/test_task1.py
> +    )
1. Попробуйте больше разных графов (в том числе интересуют крайние случаи).
2. Также нужно проверять, что то, что Вы сохранили совпадает с тем, что Вы ожидаете увидеть в файле.

2022-09-11 16:29 UTC, vadyushkins commented on .github/workflows/test.yml
> +on: [ push, pull_request, workflow_dispatch ]
Для чего Вам потребовалось отдельно ручками запускать CI? (workflow_dispatch)

2022-09-11 16:29 UTC, vadyushkins commented on project/task1.py
> +from networkx.drawing.nx_pydot import to_pydot
```suggestion
from pathlib import Path
from typing import Set
from typing import Tuple

import cfpq_data
import networkx as nx
```

2022-09-11 16:48 UTC, vadyushkins commented
> [Pull-request снабдить понятным названием и описанием с соответствующими пунктами прогресса.](https://github.com/JetBrains-Research/formal-lang-course#%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B5%D0%B3%D0%BE-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F)

# Задача 1. Инициализация рабочего окружения

* **Мягкий дедлайн**: 11.09.2021, 23:59
* **Жёсткий дедлайн**: 14.09.2021, 23:59
* Полный балл: 5

## Задача

- [x] Сделать **приватный** `fork` данного репозитория.
- [x] Добавить ссылку на ваш `fork` в [таблицу](https://docs.google.com/spreadsheets/d/1IXeAhVb_cRRQf0UwHjw2AeBqNwpcY-XcnVs3-t9HBYc/edit#gid=0).
- [x] Добавить в совладельцы форка одного из ассистентов (чтобы узнать, кого именно, нужно посмотреть в [таблицу](https://docs.google.com/spreadsheets/d/1IXeAhVb_cRRQf0UwHjw2AeBqNwpcY-XcnVs3-t9HBYc/edit#gid=0))
- [x] Реализовать модуль, предоставляющий перечисленные ниже возможности. Для работы с графами использовать [cfpq-data](https://jetbrains-research.github.io/CFPQ_Data/tutorial.html#graphs). Данный модуль в дальнейшем будет расширяться. Функции, которые необходимо реализовать:
  - [x] По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах. Для получения графа по имени использовать [эту функцию](https://jetbrains-research.github.io/CFPQ_Data/tutorial.html#get-a-real-graph).
  - [x] По количеству вершин в циклах и именам меток строить [граф из двух циклов](https://jetbrains-research.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.generators.labeled_two_cycles_graph.html#cfpq_data.graphs.generators.labeled_two_cycles_graph) и сохранять его в указанный файл в формате DOT (использовать pydot).
- [x] Добавить необходимые тесты.
- [x] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.

2022-09-11 16:53 UTC, vadyushkins commented on tests/test_task1.py
> +    )
Измоорфизм который тут проверяется как минимум не проверяет метки вершин и метки рёбер. Необходимо обеспечить проверку на равенство всех меток рёбер точно

2022-09-11 19:49 UTC, IlyaMuravjov commented on .github/workflows/test.yml
> +    runs-on: ubuntu-latest
Добавил

2022-09-11 19:49 UTC, IlyaMuravjov commented on project/task1.py
> +    """
Убрал документацию, уточнил имена

2022-09-11 19:49 UTC, IlyaMuravjov commented on requirements.txt
> +networkx
Убрал, но PyCharm по умолчанию ругается

2022-09-11 19:49 UTC, IlyaMuravjov commented on tests/test_task1.py
> +    assert actual_graph_data == expected_graph_data
Добавил больше интересных случаев

2022-09-11 19:50 UTC, IlyaMuravjov commented on tests/test_task1.py
> +    )
1. Добавил больше интересных случаев.
2. То, что я ожидаю увидеть в файле, не определено однозначно. Например, `digraph  {1;0;}` и `digraph  {0;1;}` описывают один и тот же граф с двумя узлами и без рёбер.

2022-09-11 19:51 UTC, IlyaMuravjov commented on .github/workflows/test.yml
> +on: [ push, pull_request, workflow_dispatch ]
По привычке добавил на всякий случай, но раз уже есть `push`, то, наверное, действительно, излишне. Убрал.

2022-09-11 19:51 UTC, IlyaMuravjov commented on project/task1.py
> +from networkx.drawing.nx_pydot import to_pydot
Изменил здесь и в тестах

2022-09-11 20:08 UTC, IlyaMuravjov commented on tests/test_task1.py
> +    )
1. Добавил больше интересных случаев.
2. То, что я ожидаю увидеть в файле, не определено однозначно. Например, `digraph  {1;0;}` и `digraph  {0;1;}` описывают один и тот же граф с двумя узлами и без рёбер.

Добавил проверку на равенство для всех атрибутов вершин и рёбер, а не только `label` для рёбер.

2022-09-14 08:31 UTC, vadyushkins approved these changes
В целом ок, зачтено
Дальше тестов будет больше, так что посмотрите на pytest. В том числе на https://docs.pytest.org/en/7.1.x/example/parametrize.html#parametrizing-tests.
Выносите все данные (параметры теста, expected data) в отдельный json, например, а в тесте их загружайте только.

2022-09-14 17:15 UTC, merged