Задача 3. Регулярные запросы для всех пар вершин
IlyaMuravjov/formal-lang-course pull request #3
Opened 2022-09-25 08:55 UTC by IlyaMuravjov

* **Мягкий дедлайн**: 25.09.2022, 23:59
* **Жёсткий дедлайн**: 28.09.2022, 23:59
* Полный балл: 5

## Задача

- [x] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать **функцию** пересечения двух конечных автоматов через тензорное произведение.
- [x] На основе предыдущей функции реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе.
  - Для конструирования регулярного запроса и преобразований графа использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
- [x] Добавить необходимые тесты.

2022-09-26 18:09 UTC, vadyushkins requested changes

2022-09-26 18:09 UTC, vivalerievich commented on project/bool_decomposed_nfa.py
> +from pyformlang.finite_automaton import Symbol
```suggestion
import pyformlang
```

2022-09-26 18:09 UTC, vivalerievich commented on project/bool_decomposed_nfa.py
> +    final_state_indices: Set[int]
Зачем Вам именно у объекта класса эти атрибуты, а не у его инстансов?

2022-09-26 18:09 UTC, vadyushkins commented on project/bool_decomposed_nfa.py
> +            idx_to_state=idx_to_state_dict.__getitem__,
Это вдруг зачем?

2022-09-26 18:09 UTC, vadyushkins commented on project/bool_decomposition.py
> +from scipy.sparse import kron
import scipy

2022-09-26 18:09 UTC, vadyushkins commented on project/bool_decomposition.py
> +    size: int
?

2022-09-26 18:09 UTC, vadyushkins commented on project/bool_decomposition.py
> +            for (i, j, elm) in content:
elm?

2022-09-26 18:09 UTC, vadyushkins commented on project/fa_utils.py
> +from project.bool_decomposed_nfa import BoolDecomposedNFA
__all__ должно быть после всех импортов

2022-09-28 19:41 UTC, IlyaMuravjov commented on project/bool_decomposed_nfa.py
> +from pyformlang.finite_automaton import Symbol
Заменил, но очень громоздко получается.

2022-09-28 19:41 UTC, IlyaMuravjov commented on project/bool_decomposed_nfa.py
> +    final_state_indices: Set[int]
Убрал. Не знал, что Python так работает, не приходилось им до этого пользоваться. Спасибо, что обратили на это внимание.

2022-09-28 19:42 UTC, IlyaMuravjov commented on project/bool_decomposed_nfa.py
> +            idx_to_state=idx_to_state_dict.__getitem__,
Если вопрос про само поле `idx_to_state`, то оно нужно, чтобы после того, как всё отработает, вернуть, не то, что, например, узел, который мы занумеровали третьим, достижим из пятого, а то, какой именно узел достижим из какого именно узла. 

А если вопрос про `__getitem__`, то оно здесь, потому что при создании `BoolDecomposedNFA` для пересечения автоматов туда записывается более сложна функция:
```python
idx_to_state=lambda i: pyformlang.finite_automaton.State(
                     (
                           self.idx_to_state(i // other.state_count),
                           (other.idx_to_state(i % other.state_count)),
                     )
            )
```

2022-09-28 19:42 UTC, IlyaMuravjov commented on project/bool_decomposition.py
> +from scipy.sparse import kron
Заменил

2022-09-28 19:43 UTC, IlyaMuravjov commented on project/bool_decomposition.py
> +    size: int
Убрал

2022-09-28 19:44 UTC, IlyaMuravjov commented on project/bool_decomposition.py
> +            for (i, j, elm) in content:
Заменил на `element`. Если вопрос был: "Почему не `label`?", то это, потому что я специально сделал более общую абстракцию для булевой декомпозиции произвольной матрицы, элементы которой -- множества (необязательно для матрицы смежности конечного автомата). Так как, судя по тому, что у нас на лекциях, такая конструкция довольно часто используется.

2022-09-28 19:44 UTC, IlyaMuravjov commented on project/fa_utils.py
> +from project.bool_decomposed_nfa import BoolDecomposedNFA
Исправил

2022-09-28 19:46 UTC, IlyaMuravjov commented
Отключил тест `get_graph_data`, так как `cfpq_data` теперь падает при попытки скачать граф.

2022-09-30 09:42 UTC, vadyushkins approved these changes
в целом норм, зачтено
поправьте пожалуйста тесты - один json на один тест (функция \ метод)

2022-10-02 14:27 UTC, merged